/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminCallbacksRouteImport } from './routes/admin/callbacks'
import { Route as AdminCoursesRouteImport } from './routes/admin/courses'
import { Route as AdminEnquiriesRouteImport } from './routes/admin/enquiries'
import { Route as AdminEnrollmentsRouteImport } from './routes/admin/enrollments'
import { Route as AdminMentorsRouteImport } from './routes/admin/mentors'
import { Route as AdminProjectsRouteImport } from './routes/admin/projects'
import { Route as AdminProposalsRouteImport } from './routes/admin/proposals'
import { Route as AdminStudentsRouteImport } from './routes/admin/students'
import { Route as AdminTestimonialsRouteImport } from './routes/admin/testimonials'
import { Route as StoriesSlugRouteImport } from './routes/stories.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCallbacksRoute = AdminCallbacksRouteImport.update({
  id: '/callbacks',
  path: '/callbacks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEnquiriesRoute = AdminEnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEnrollmentsRoute = AdminEnrollmentsRouteImport.update({
  id: '/enrollments',
  path: '/enrollments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMentorsRoute = AdminMentorsRouteImport.update({
  id: '/mentors',
  path: '/mentors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProposalsRoute = AdminProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AdminRoute,
} as any)
const StoriesSlugRoute = StoriesSlugRouteImport.update({
  id: '/stories/$slug',
  path: '/stories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/courses': typeof CoursesRoute
  '/admin/callbacks': typeof AdminCallbacksRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/enrollments': typeof AdminEnrollmentsRoute
  '/admin/mentors': typeof AdminMentorsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/proposals': typeof AdminProposalsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/courses': typeof CoursesRoute
  '/admin/callbacks': typeof AdminCallbacksRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/enrollments': typeof AdminEnrollmentsRoute
  '/admin/mentors': typeof AdminMentorsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/proposals': typeof AdminProposalsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/courses': typeof CoursesRoute
  '/admin/callbacks': typeof AdminCallbacksRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/enrollments': typeof AdminEnrollmentsRoute
  '/admin/mentors': typeof AdminMentorsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/proposals': typeof AdminProposalsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/stories/$slug': typeof StoriesSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/courses'
    | '/admin/callbacks'
    | '/admin/courses'
    | '/admin/enquiries'
    | '/admin/enrollments'
    | '/admin/mentors'
    | '/admin/projects'
    | '/admin/proposals'
    | '/admin/students'
    | '/admin/testimonials'
    | '/stories/$slug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/courses'
    | '/admin/callbacks'
    | '/admin/courses'
    | '/admin/enquiries'
    | '/admin/enrollments'
    | '/admin/mentors'
    | '/admin/projects'
    | '/admin/proposals'
    | '/admin/students'
    | '/admin/testimonials'
    | '/stories/$slug'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/courses'
    | '/admin/callbacks'
    | '/admin/courses'
    | '/admin/enquiries'
    | '/admin/enrollments'
    | '/admin/mentors'
    | '/admin/projects'
    | '/admin/proposals'
    | '/admin/students'
    | '/admin/testimonials'
    | '/stories/$slug'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CoursesRoute: typeof CoursesRoute
  StoriesSlugRoute: typeof StoriesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/callbacks': {
      id: '/admin/callbacks'
      path: '/callbacks'
      fullPath: '/admin/callbacks'
      preLoaderRoute: typeof AdminCallbacksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/enquiries': {
      id: '/admin/enquiries'
      path: '/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AdminEnquiriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/enrollments': {
      id: '/admin/enrollments'
      path: '/enrollments'
      fullPath: '/admin/enrollments'
      preLoaderRoute: typeof AdminEnrollmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mentors': {
      id: '/admin/mentors'
      path: '/mentors'
      fullPath: '/admin/mentors'
      preLoaderRoute: typeof AdminMentorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/proposals': {
      id: '/admin/proposals'
      path: '/proposals'
      fullPath: '/admin/proposals'
      preLoaderRoute: typeof AdminProposalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/stories/$slug': {
      id: '/stories/$slug'
      path: '/stories/$slug'
      fullPath: '/stories/$slug'
      preLoaderRoute: typeof StoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminCallbacksRoute: typeof AdminCallbacksRoute
  AdminCoursesRoute: typeof AdminCoursesRoute
  AdminEnquiriesRoute: typeof AdminEnquiriesRoute
  AdminEnrollmentsRoute: typeof AdminEnrollmentsRoute
  AdminMentorsRoute: typeof AdminMentorsRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminProposalsRoute: typeof AdminProposalsRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCallbacksRoute: AdminCallbacksRoute,
  AdminCoursesRoute: AdminCoursesRoute,
  AdminEnquiriesRoute: AdminEnquiriesRoute,
  AdminEnrollmentsRoute: AdminEnrollmentsRoute,
  AdminMentorsRoute: AdminMentorsRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminProposalsRoute: AdminProposalsRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CoursesRoute: CoursesRoute,
  StoriesSlugRoute: StoriesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
